
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMMA DOT EQUALS ID INT LP METHOD_INQ METHOD_MoveUp RP STRINGstatement : method\n                    | assignment\n                    | empty\n                   assignment : stu_assignment\n                  | method_assignment\n                    method : method_moveup\n                | method_inqmethod_moveup : ID DOT METHOD_MoveUp LP RP method_inq : ID DOT METHOD_INQ LP RP stu_assignment : ID EQUALS IDmethod_assignment : ID EQUALS method_inqempty :  '
    
_lr_action_items = {'$end':([0,1,2,3,4,5,6,7,8,14,15,19,20,],[-12,0,-1,-2,-3,-6,-7,-4,-5,-10,-11,-8,-9,]),'ID':([0,11,],[9,14,]),'DOT':([9,14,],[10,18,]),'EQUALS':([9,],[11,]),'METHOD_MoveUp':([10,],[12,]),'METHOD_INQ':([10,18,],[13,13,]),'LP':([12,13,],[16,17,]),'RP':([16,17,],[19,20,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'method':([0,],[2,]),'assignment':([0,],[3,]),'empty':([0,],[4,]),'method_moveup':([0,],[5,]),'method_inq':([0,11,],[6,15,]),'stu_assignment':([0,],[7,]),'method_assignment':([0,],[8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> method','statement',1,'p_statement','Macro_parser.py',16),
  ('statement -> assignment','statement',1,'p_statement','Macro_parser.py',17),
  ('statement -> empty','statement',1,'p_statement','Macro_parser.py',18),
  ('assignment -> stu_assignment','assignment',1,'p_assignment','Macro_parser.py',25),
  ('assignment -> method_assignment','assignment',1,'p_assignment','Macro_parser.py',26),
  ('method -> method_moveup','method',1,'p_method','Macro_parser.py',32),
  ('method -> method_inq','method',1,'p_method','Macro_parser.py',33),
  ('method_moveup -> ID DOT METHOD_MoveUp LP RP','method_moveup',5,'p_method_moveup','Macro_parser.py',40),
  ('method_inq -> ID DOT METHOD_INQ LP RP','method_inq',5,'p_method_inq','Macro_parser.py',59),
  ('stu_assignment -> ID EQUALS ID','stu_assignment',3,'p_stu_assignment','Macro_parser.py',75),
  ('method_assignment -> ID EQUALS method_inq','method_assignment',3,'p_method_assignment','Macro_parser.py',87),
  ('empty -> <empty>','empty',0,'p_empty','Macro_parser.py',93),
]
